export const FETCH_TODOS_START = 'FETCH_TODOS_START';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAILED = 'FETCH_TODOS_FAILED';

export const ADD_TODO_START = 'ADD_TODO_START';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';

export const REMOVE_TODO_START = 'REMOVE_TODO_START';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_FAILED = 'REMOVE_TODO_FAILED';

export const EDIT_TODO_START = 'EDIT_TODO';
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
export const EDIT_TODO_FAILED = 'EDIT_TODO_FAILED';


export const CHECK_TODO_START = 'CHECK_TODO_START';
export const CHECK_TODO_SUCCESS = 'CHECK_TODO_SUCCESS';
export const CHECK_TODO_FAILED = 'CHECK_TODO_FAILED';


export const CHECK_TODO_NAME_START = 'CHECK_TODO_NAME_START';
export const CHECK_TODO_NAME_SUCCESS = 'CHECK_TODO_NAME_SUCCESS';
export const CHECK_TODO_NAME_FAILED = 'CHECK_TODO_NAME_FAILED';


